# Generated by Django 4.0.3 on 2022-05-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=300)),
                ('airfield_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(max_length=300)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='centeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_origin', models.CharField(max_length=300)),
                ('airfield_origin', models.CharField(max_length=300)),
                ('destination_city', models.CharField(max_length=300)),
                ('destination_airport', models.CharField(max_length=300)),
                ('datetime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('transport', models.CharField(max_length=300)),
                ('centeral_class', models.CharField(max_length=300)),
                ('airplane_type', models.CharField(max_length=300)),
                ('reserved', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
